# Generated by Django 2.2.1 on 2019-05-15 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190515_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 15, 5, 47, 0, 449545, tzinfo=utc)),
        ),
    ]
